export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Billy Stoltenberg',
    'Eloise Ebert',
    'Teresa Luettgen',
    'Salvador Mayert',
    'Dr. Guadalupe Rath',
    'Kelvin Pouros',
    'Thelma Langworth',
    'Kristen Wunsch',
    'Steve Welch',
    'Brian Jacobs',
    'Lillie Schultz',
    'Mr. Conrad Spinka',
    'Charlene Krajcik',
    'Kerry Kuhlman',
    'Betty Hammes',
    'Tony Paucek PhD',
    'Sherri Davis',
    'Angel Rolfson-Kulas',
    'Dr. Lee Doyle-Grant',
    'Cheryl Romaguera',
    'Billy Braun',
    'Adam Trantow',
    'Brandon Von',
    'Willis Ankunding',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Medhurst, Moore and Franey',
    'Hahn, Homenick and Lind',
    'Larkin LLC',
    'Stamm, Larson and Mertz',
    'Spencer, Raynor and Langosh',
    'Lehner - Feeney',
    'Leuschke, Harris and Kuhlman',
    'Gutmann - Kassulke',
    'Turcotte - Runolfsson',
    'Howe - Anderson',
    'Sipes - Yost',
    'Johns - Aufderhar',
    'Schmidt LLC',
    'Smitham - Gerlach',
    'Waelchi - VonRueden',
    'Padberg - Macejkovic',
    'Lemke - Ferry',
    'Koch and Sons',
    'Klein - Rolfson',
    'Weimann LLC',
    'White, Cassin and Goldner',
    'Mohr, Langworth and Hills',
    'Mitchell, Volkman and Prosacco',
    'Streich Group',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [
    'Reminder: Parent-Teacher Conference Next Week',
    'School Intramurals Opening Ceremony on Monday',
    'Science Fair 2025: Registration Now Open',
    'Library Extends Hours for Exam Week',
    'Campus Cleanup Drive Volunteers Needed',
    'Graduating Class Picture Day Scheduled',
    'New School Uniform Policy Effective This Semester',
    'Scholarship Applications Open Until October 15',
    'Math Olympiad Training Begins This Saturday',
    'Student Council Election Results Announced',
    'Free Health Check-up for All Students Next Friday',
    'Art Exhibit by Grade 10 Students at the Gym',
    'Important: Fire Drill Scheduled Tomorrow',
    'Join the English Debate Team – Tryouts This Week',
    'School Band Practice Resumes After Break',
    'Basketball Varsity Game vs. Central High',
    'Field Trip to the Science Museum for Grade 8',
    'Campus Wi-Fi Upgrade Completed',
    'New Cafeteria Menu Items Available',
    'Congratulations to Honor Roll Awardees',
    'Lost and Found Items to Be Claimed at the Office',
    'Guidance Office Opens Peer Support Program',
    'Special Assembly: Guest Speaker on Leadership',
    'School Closing Early Due to Weather Advisory',
  ][index];

export const _description = (index: number) =>
  [
    'Parents are reminded that the Parent-Teacher Conference will be held next week. Please check your child’s schedule for the exact time slot.',
    'The school intramurals will officially open with a ceremony on Monday morning. All students are expected to attend and wear their PE uniforms.',
    'The annual Science Fair is fast approaching! Students interested in joining may now register at the Science Department until October 10.',
    'The library will extend operating hours until 8:00 PM to accommodate students preparing for midterm exams.',
    'The Environmental Club is seeking volunteers for the campus cleanup drive this Saturday. Join us and earn community service hours.',
    'Graduating students are reminded that the official class picture day will be on Friday. Please wear your complete school uniform.',
    'A new uniform policy takes effect this semester. Kindly review the updated dress code guidelines posted on the school website.',
    'Applications for academic scholarships are now open. Deadline for submission of requirements is October 15.',
    'Students representing the school in the Math Olympiad are invited to attend the first training session this Saturday at Room 301.',
    'Congratulations to the newly elected student council officers! Full list of winners has been posted on the bulletin boards.',
    'The school clinic will provide free medical check-ups for all students next Friday. Please bring your school ID.',
    'Grade 10 students will showcase their artworks in an exhibit at the gymnasium this Wednesday. Everyone is invited to attend.',
    'A fire drill is scheduled tomorrow at 9:00 AM. All students and faculty must participate and follow safety protocols.',
    'Students interested in debate may join the English Debate Team tryouts happening this Thursday at the auditorium.',
    'School band rehearsals resume after the break. Members are reminded to bring their instruments on Wednesday.',
    'The basketball varsity team will face Central High this weekend at the school gym. Let’s cheer for our players!',
    'Grade 8 students will visit the Science Museum for their field trip next week. Permission slips must be submitted by Friday.',
    'The IT Department has completed the campus Wi-Fi upgrade. Students should now experience faster and more reliable connections.',
    'The cafeteria has added new healthy menu options starting this week. Check out the salad and fruit bar!',
    'Congratulations to all students who made it to the honor roll this quarter. Certificates will be distributed on Monday.',
    'Students may claim lost and found items at the Administrative Office before the end of the month.',
    'The Guidance Office has launched a peer support program to help students cope with stress and academic challenges.',
    'A special assembly will be held with a guest speaker on leadership and motivation this Thursday at the auditorium.',
    'Due to a weather advisory, the school will close early today at 1:00 PM. Please arrange for pickup accordingly.',
  ][index];


export const _taskNames = (index: number) =>
  [
    `Prepare Monthly Financial Report`,
    `Design New Marketing Campaign`,
    `Analyze Customer Feedback`,
    `Update Website Content`,
    `Conduct Market Research`,
    `Develop Software Application`,
    `Organize Team Meeting`,
    `Create Social Media Posts`,
    `Review Project Plan`,
    `Implement Security Protocols`,
    `Write Technical Documentation`,
    `Test New Product Features`,
    `Manage Client Inquiries`,
    `Train New Employees`,
    `Coordinate Logistics`,
    `Monitor Network Performance`,
    `Develop Training Materials`,
    `Draft Press Release`,
    `Prepare Budget Proposal`,
    `Evaluate Vendor Proposals`,
    `Perform Data Analysis`,
    `Conduct Quality Assurance`,
    `Plan Event Logistics`,
    `Optimize SEO Strategies`,
  ][index];

export const _productNames = (index: number) =>
  [
    'Nike Air Force 1 NDESTRUKT',
    'Nike Space Hippie 04',
    'Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear',
    'Nike Blazer Low 77 Vintage',
    'Nike ZoomX SuperRep Surge',
    'Zoom Freak 2',
    'Nike Air Max Zephyr',
    'Jordan Delta',
    'Air Jordan XXXV PF',
    'Nike Waffle Racer Crater',
    'Kyrie 7 EP Sisterhood',
    'Nike Air Zoom BB NXT',
    'Nike Air Force 1 07 LX',
    'Nike Air Force 1 Shadow SE',
    'Nike Air Zoom Tempo NEXT%',
    'Nike DBreak-Type',
    'Nike Air Max Up',
    'Nike Air Max 270 React ENG',
    'NikeCourt Royale',
    'Nike Air Zoom Pegasus 37 Premium',
    'Nike Air Zoom SuperRep',
    'NikeCourt Royale',
    'Nike React Art3mis',
    'Nike React Infinity Run Flyknit A.I.R. Chaz Bear',
  ][index];
