<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PatchUpdates\OtherFeesAccountBalance;
use Carbon\Carbon;

class OtherFeesAccountBalanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            // ============================================================
            // ATHENEUM - Mitch Cipriaso (09459759771)
            // ============================================================
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000001',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 7',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-01',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 5000.00,
                'discount' => 500.00,
                'paid_amount' => 1500.00,
                'account_balance' => 3000.00,
                'last_payment_date' => '2026-08-05',
                'last_reference_number' => 'SI-ATH-001',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000001',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 7',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-01',
                'fee_name' => 'School Uniform',
                'orig_amount' => 2500.00,
                'discount' => 0.00,
                'paid_amount' => 2500.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-05',
                'last_reference_number' => 'SI-ATH-002',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000002',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 8',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '2ND SEMESTER',
                'transaction_date' => '2026-08-02',
                'fee_name' => 'Grade 8 Books',
                'orig_amount' => 4500.00,
                'discount' => 300.00,
                'paid_amount' => 0.00,
                'account_balance' => 4200.00,
                'last_payment_date' => null,
                'last_reference_number' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // SCA - Sheena Navarra (09165620305)
            // ============================================================
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000003',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 7',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-03',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 5500.00,
                'discount' => 500.00,
                'paid_amount' => 5500.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-10',
                'last_reference_number' => 'SI-SCA-001',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000003',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 7',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-03',
                'fee_name' => 'School ID',
                'orig_amount' => 200.00,
                'discount' => 0.00,
                'paid_amount' => 200.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-10',
                'last_reference_number' => 'SI-SCA-002',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000004',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 8',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-04',
                'fee_name' => 'Grade 8 Books',
                'orig_amount' => 6000.00,
                'discount' => 400.00,
                'paid_amount' => 3000.00,
                'account_balance' => 2600.00,
                'last_payment_date' => '2026-08-12',
                'last_reference_number' => 'SI-SCA-003',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Roxanne Villaruel (09533786679)
            // ============================================================
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000005',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-05',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 5000.00,
                'discount' => 300.00,
                'paid_amount' => 5000.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-15',
                'last_reference_number' => 'SI-GVA-001',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000006',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 8',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '2ND SEMESTER',
                'transaction_date' => '2026-08-06',
                'fee_name' => 'Grade 8 Books',
                'orig_amount' => 5200.00,
                'discount' => 200.00,
                'paid_amount' => 2000.00,
                'account_balance' => 3000.00,
                'last_payment_date' => '2026-08-18',
                'last_reference_number' => 'SI-GVA-002',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000006',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 8',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '2ND SEMESTER',
                'transaction_date' => '2026-08-06',
                'fee_name' => 'Science Laboratory Fee',
                'orig_amount' => 1500.00,
                'discount' => 0.00,
                'paid_amount' => 0.00,
                'account_balance' => 1500.00,
                'last_payment_date' => null,
                'last_reference_number' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Mary Ruth Joy Uy (09292784580)
            // ============================================================
            [
                'userid' => '09292784580',
                'school_code' => 'gva',
                'student_id' => '20260000007',
                'student_name' => 'Uy, Mary Ruth Joy',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-07',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 4800.00,
                'discount' => 0.00,
                'paid_amount' => 0.00,
                'account_balance' => 4800.00,
                'last_payment_date' => null,
                'last_reference_number' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Alma Villota Dulay (09484131577)
            // ============================================================
            [
                'userid' => '09484131577',
                'school_code' => 'gva',
                'student_id' => '20260000008',
                'student_name' => 'Dulay, Alma Villota',
                'level' => 'GRADE 9',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-08',
                'fee_name' => 'Grade 9 Books',
                'orig_amount' => 6000.00,
                'discount' => 400.00,
                'paid_amount' => 3500.00,
                'account_balance' => 2100.00,
                'last_payment_date' => '2026-08-20',
                'last_reference_number' => 'SI-GVA-003',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Lilibeth Delos Santos (09953344438)
            // ============================================================
            [
                'userid' => '09953344438',
                'school_code' => 'gva',
                'student_id' => '20260000009',
                'student_name' => 'Delos Santos, Lilibeth',
                'level' => 'GRADE 10',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-09',
                'fee_name' => 'Grade 10 Books',
                'orig_amount' => 6500.00,
                'discount' => 500.00,
                'paid_amount' => 6500.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-22',
                'last_reference_number' => 'SI-GVA-004',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Aileen Bonavente (09067850846)
            // ============================================================
            [
                'userid' => '09067850846',
                'school_code' => 'gva',
                'student_id' => '20260000010',
                'student_name' => 'Bonavente, Aileen',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-10',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 5000.00,
                'discount' => 200.00,
                'paid_amount' => 2500.00,
                'account_balance' => 2300.00,
                'last_payment_date' => '2026-08-25',
                'last_reference_number' => 'SI-GVA-005',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Giezzelle Del Rosario (09052223875)
            // ============================================================
            [
                'userid' => '09052223875',
                'school_code' => 'gva',
                'student_id' => '20260000011',
                'student_name' => 'Del Rosario, Giezzelle C.',
                'level' => 'GRADE 8',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-11',
                'fee_name' => 'Grade 8 Books',
                'orig_amount' => 5500.00,
                'discount' => 300.00,
                'paid_amount' => 1000.00,
                'account_balance' => 4200.00,
                'last_payment_date' => '2026-08-28',
                'last_reference_number' => 'SI-GVA-006',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Louie Santos (09973947883)
            // ============================================================
            [
                'userid' => '09973947883',
                'school_code' => 'gva',
                'student_id' => '20260000012',
                'student_name' => 'Santos, Louie',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-12',
                'fee_name' => 'Grade 7 Books',
                'orig_amount' => 5000.00,
                'discount' => 200.00,
                'paid_amount' => 5000.00,
                'account_balance' => 0.00,
                'last_payment_date' => '2026-08-30',
                'last_reference_number' => 'SI-GVA-007',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09973947883',
                'school_code' => 'gva',
                'student_id' => '20260000012',
                'student_name' => 'Santos, Louie',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'transaction_date' => '2026-08-12',
                'fee_name' => 'Computer Laboratory Fee',
                'orig_amount' => 2000.00,
                'discount' => 0.00,
                'paid_amount' => 0.00,
                'account_balance' => 2000.00,
                'last_payment_date' => null,
                'last_reference_number' => null,
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($records as $record) {
            OtherFeesAccountBalance::create($record);
        }
    }
}