<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PatchUpdates\PaymentTransaction;
use Carbon\Carbon;

class PaymentTransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            // ============================================================
            // ATHENEUM - Mitch Cipriaso (09459759771)
            // ============================================================
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000001',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 7',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1000.00,
                'payment_date' => '2026-08-05 08:08:00',
                'transaction_reference' => 'PAY-ATH-001',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000001',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 7',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'GCASH',
                'payment_description' => 'Miscellaneous Fees',
                'payment_amount' => 500.00,
                'payment_date' => '2026-08-06 09:15:00',
                'transaction_reference' => 'PAY-ATH-002',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09459759771',
                'school_code' => 'atheneum',
                'student_id' => '20260000002',
                'student_name' => 'Cipriaso, Mitch',
                'level' => 'GRADE 8',
                'section_course' => 'ATHENEUM',
                'school_year' => '2026-2027',
                'school_term' => '2ND SEMESTER',
                'payment_method' => 'BANK TRANSFER',
                'payment_description' => 'Tuition Fees for August, 2026',
                'payment_amount' => 1500.00,
                'payment_date' => '2026-08-10 10:30:00',
                'transaction_reference' => 'PAY-ATH-003',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // SCA - Sheena Navarra (09165620305)
            // ============================================================
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000003',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 7',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1200.00,
                'payment_date' => '2026-08-15 08:00:00',
                'transaction_reference' => 'PAY-SCA-001',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000003',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 7',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'PAYPAL',
                'payment_description' => 'School ID Fee',
                'payment_amount' => 200.00,
                'payment_date' => '2026-08-16 09:30:00',
                'transaction_reference' => 'PAY-SCA-002',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09165620305',
                'school_code' => 'sca',
                'student_id' => '20260000004',
                'student_name' => 'Navarra, Sheena',
                'level' => 'GRADE 8',
                'section_course' => 'SCA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for August, 2026',
                'payment_amount' => 1300.00,
                'payment_date' => '2026-08-20 08:45:00',
                'transaction_reference' => 'PAY-SCA-003',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Roxanne Villaruel (09533786679)
            // ============================================================
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000005',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1000.00,
                'payment_date' => '2026-08-08 08:15:00',
                'transaction_reference' => 'PAY-GVA-001',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000005',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'GCASH',
                'payment_description' => 'Books and Supplies',
                'payment_amount' => 800.00,
                'payment_date' => '2026-08-09 10:00:00',
                'transaction_reference' => 'PAY-GVA-002',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09533786679',
                'school_code' => 'gva',
                'student_id' => '20260000006',
                'student_name' => 'Villaruel, Roxanne',
                'level' => 'GRADE 8',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '2ND SEMESTER',
                'payment_method' => 'BANK TRANSFER',
                'payment_description' => 'Tuition Fees for August, 2026',
                'payment_amount' => 1200.00,
                'payment_date' => '2026-08-12 09:20:00',
                'transaction_reference' => 'PAY-GVA-003',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Mary Ruth Joy Uy (09292784580)
            // ============================================================
            [
                'userid' => '09292784580',
                'school_code' => 'gva',
                'student_id' => '20260000007',
                'student_name' => 'Uy, Mary Ruth Joy',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 900.00,
                'payment_date' => '2026-08-01 08:30:00',
                'transaction_reference' => 'PAY-GVA-004',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Alma Villota Dulay (09484131577)
            // ============================================================
            [
                'userid' => '09484131577',
                'school_code' => 'gva',
                'student_id' => '20260000008',
                'student_name' => 'Dulay, Alma Villota',
                'level' => 'GRADE 9',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1400.00,
                'payment_date' => '2026-08-18 08:00:00',
                'transaction_reference' => 'PAY-GVA-005',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09484131577',
                'school_code' => 'gva',
                'student_id' => '20260000008',
                'student_name' => 'Dulay, Alma Villota',
                'level' => 'GRADE 9',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'GCASH',
                'payment_description' => 'Laboratory Fees',
                'payment_amount' => 600.00,
                'payment_date' => '2026-08-19 09:45:00',
                'transaction_reference' => 'PAY-GVA-006',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Lilibeth Delos Santos (09953344438)
            // ============================================================
            [
                'userid' => '09953344438',
                'school_code' => 'gva',
                'student_id' => '20260000009',
                'student_name' => 'Delos Santos, Lilibeth',
                'level' => 'GRADE 10',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1500.00,
                'payment_date' => '2026-08-22 08:15:00',
                'transaction_reference' => 'PAY-GVA-007',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09953344438',
                'school_code' => 'gva',
                'student_id' => '20260000009',
                'student_name' => 'Delos Santos, Lilibeth',
                'level' => 'GRADE 10',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'PAYPAL',
                'payment_description' => 'Books and Supplies',
                'payment_amount' => 700.00,
                'payment_date' => '2026-08-23 10:30:00',
                'transaction_reference' => 'PAY-GVA-008',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Aileen Bonavente (09067850846)
            // ============================================================
            [
                'userid' => '09067850846',
                'school_code' => 'gva',
                'student_id' => '20260000010',
                'student_name' => 'Bonavente, Aileen',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for August, 2026',
                'payment_amount' => 1100.00,
                'payment_date' => '2026-08-25 08:45:00',
                'transaction_reference' => 'PAY-GVA-009',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Giezzelle Del Rosario (09052223875)
            // ============================================================
            [
                'userid' => '09052223875',
                'school_code' => 'gva',
                'student_id' => '20260000011',
                'student_name' => 'Del Rosario, Giezzelle C.',
                'level' => 'GRADE 8',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1000.00,
                'payment_date' => '2026-08-28 08:30:00',
                'transaction_reference' => 'PAY-GVA-010',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ============================================================
            // GVA - Louie Santos (09973947883)
            // ============================================================
            [
                'userid' => '09973947883',
                'school_code' => 'gva',
                'student_id' => '20260000012',
                'student_name' => 'Santos, Louie',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'CASH',
                'payment_description' => 'Tuition Fees for July, 2026',
                'payment_amount' => 1000.00,
                'payment_date' => '2026-08-30 08:00:00',
                'transaction_reference' => 'PAY-GVA-011',
                'cashier' => 'Cashier 1',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'userid' => '09973947883',
                'school_code' => 'gva',
                'student_id' => '20260000012',
                'student_name' => 'Santos, Louie',
                'level' => 'GRADE 7',
                'section_course' => 'GVA',
                'school_year' => '2026-2027',
                'school_term' => '1ST SEMESTER',
                'payment_method' => 'GCASH',
                'payment_description' => 'School ID and Uniform',
                'payment_amount' => 800.00,
                'payment_date' => '2026-08-31 09:15:00',
                'transaction_reference' => 'PAY-GVA-012',
                'cashier' => 'Cashier 2',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($records as $record) {
            PaymentTransaction::create($record);
        }
    }
}