<?php

namespace App\Models\PatchUpdates;

use App\Models\PatchUpdates\Base\SchoolBaseModel;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class MonthlyAccountBalance extends SchoolBaseModel
{
    use HasFactory;

    protected $table = 'monthly_account_balance';

    protected $fillable = [
        'userid',
        'school_code',
        'student_id',
        'student_name',
        'enrollment_date',
        'enrollment_number',
        'level',
        'section_course',
        'school_year',
        'school_term',
        'payment_mode',
        'month_1_duedate',
        'month_1_orig_amount',
        'month_1_paid_amount',
        'month_1_account_balance',
        'month_1_status',
        'month_2_duedate',
        'month_2_orig_amount',
        'month_2_paid_amount',
        'month_2_account_balance',
        'month_2_status',
        'month_3_duedate',
        'month_3_orig_amount',
        'month_3_paid_amount',
        'month_3_account_balance',
        'month_3_status',
        'month_4_duedate',
        'month_4_orig_amount',
        'month_4_paid_amount',
        'month_4_account_balance',
        'month_4_status',
        'month_5_duedate',
        'month_5_orig_amount',
        'month_5_paid_amount',
        'month_5_account_balance',
        'month_5_status',
        'month_6_duedate',
        'month_6_orig_amount',
        'month_6_paid_amount',
        'month_6_account_balance',
        'month_6_status',
        'month_7_duedate',
        'month_7_orig_amount',
        'month_7_paid_amount',
        'month_7_account_balance',
        'month_7_status',
        'month_8_duedate',
        'month_8_orig_amount',
        'month_8_paid_amount',
        'month_8_account_balance',
        'month_8_status',
        'month_9_duedate',
        'month_9_orig_amount',
        'month_9_paid_amount',
        'month_9_account_balance',
        'month_9_status',
        'month_10_duedate',
        'month_10_orig_amount',
        'month_10_paid_amount',
        'month_10_account_balance',
        'month_10_status',
        'status',
    ];

    protected $casts = [
        'enrollment_date' => 'date',
        'month_1_duedate' => 'date',
        'month_2_duedate' => 'date',
        'month_3_duedate' => 'date',
        'month_4_duedate' => 'date',
        'month_5_duedate' => 'date',
        'month_6_duedate' => 'date',
        'month_7_duedate' => 'date',
        'month_8_duedate' => 'date',
        'month_9_duedate' => 'date',
        'month_10_duedate' => 'date',
        'month_1_orig_amount' => 'decimal:2',
        'month_1_paid_amount' => 'decimal:2',
        'month_1_account_balance' => 'decimal:2',
        'month_2_orig_amount' => 'decimal:2',
        'month_2_paid_amount' => 'decimal:2',
        'month_2_account_balance' => 'decimal:2',
        'month_3_orig_amount' => 'decimal:2',
        'month_3_paid_amount' => 'decimal:2',
        'month_3_account_balance' => 'decimal:2',
        'month_4_orig_amount' => 'decimal:2',
        'month_4_paid_amount' => 'decimal:2',
        'month_4_account_balance' => 'decimal:2',
        'month_5_orig_amount' => 'decimal:2',
        'month_5_paid_amount' => 'decimal:2',
        'month_5_account_balance' => 'decimal:2',
        'month_6_orig_amount' => 'decimal:2',
        'month_6_paid_amount' => 'decimal:2',
        'month_6_account_balance' => 'decimal:2',
        'month_7_orig_amount' => 'decimal:2',
        'month_7_paid_amount' => 'decimal:2',
        'month_7_account_balance' => 'decimal:2',
        'month_8_orig_amount' => 'decimal:2',
        'month_8_paid_amount' => 'decimal:2',
        'month_8_account_balance' => 'decimal:2',
        'month_9_orig_amount' => 'decimal:2',
        'month_9_paid_amount' => 'decimal:2',
        'month_9_account_balance' => 'decimal:2',
        'month_10_orig_amount' => 'decimal:2',
        'month_10_paid_amount' => 'decimal:2',
        'month_10_account_balance' => 'decimal:2',
    ];
}